export const pokeActionTypes = {
    GETALL_GENERATIONS: 'GET_GENERATIONS_REQUEST',
    GETALL_GENERATIONS_SUCCESS: 'GET_GENERATIONS_SUCCESS',

    GET_GENERATION: 'GET_GENERATIONDATA_REQUEST',
    GET_GENERATION_SUCCESS: 'GET_GENERATIONDATA_SUCCESS',
    GET_GENERATION_FAILURE: 'GET_GENERATIONDATA_FAILURE',

    GET_SPECIES: 'GET_SPECIESDATA_REQUEST',
    GET_SPECIES_SUCCESS: 'GET_SPECIESDATA_SUCCESS',
    GET_SPECIES_FAILURE: 'GET_SPECIESDATA_FAILURE',

    GET_POKEMON: 'GET_POKEMONDATA_REQUEST',
    GET_POKEMON_SUCCESS: 'GET_POKEMONDATA_SUCCESS',
    GET_POKEMON_FAILURE: 'GET_POKEMONDATA_FAILURE',
    
    GETALL_POKEMON: 'ALLPOKEMON_REQUEST',

    GETALL_POKEMON_SPECIES: 'ALLSPECIES_REQUEST'   
};